beacon:
  # known object width (cm)
  real_width: 8.5
  # camera-lenses real world distance (cm) from robot centre
  distance_from_reference_pic: 7
  # colour boundaries when in HSV: H (0-180) | S (0-255) | V (0-255)
  hsv_color_boundaries:
  - - !!python/tuple # Red
      - [5, 180 , 130]
      - [10, 230 , 190]
  - - !!python/tuple # Blue
      - [70,70, 90]
      - [90,220,170]
  - - !!python/tuple # Purple
      - [100,10,60]
      - [120,105,105]
  - - !!python/tuple # Yellow
      - [25,200,90]
      - [40, 255, 210 ]
  - - !!python/tuple # Orange
      - [180,255,255]
      - [180,255        , 255] 
  rgb_color_boundaries:
  - - !!python/tuple # Red 
      - [70, 60, 200]
      - [150, 110, 250]
  - - !!python/tuple # Blue
      - [160, 160, 0]
      - [255, 255, 60]
  - - !!python/tuple # Purple
      - [95, 80, 95]
      - [130, 110, 120]
  - - !!python/tuple # Yellow
      - [30, 130, 130]
      - [80, 170, 160]
  - - !!python/tuple # Orange
      - [70, 100, 190]
      - [145, 140, 240] 

camera: 
  focal_length: 4305 
  # x-centre-coordinate of the 2596x1944 resolution picture
  pic_centre_width: 1296
  vertical_servo_pin: 27

grid:
  #grid_size: 25
  #cell_size: 10
  #distance_to_neighbours: 30 
  #destination: ["13:18:W","18:18:W"]
  #obstacles : [[[0,90],[99,110]],[[176,0],[249,99]]] 
  #columns: 25
  #rows: 25
  #goal: !!python/tuple [13, 18]
  #start: !!python/tuple [0, 0]
  #beacons_columns: [10, 20, 0, 20, 0]
  #beacons_rows: [20, 10, 20, 20, 10]
  #orientation_reference_row: 20
  grid_size: 5
  cell_size: 50
  distance_to_neighbours: 30 
  destination: ["2:3:W","1:2:E"]
  obstacles : [[[0,90],[99,110]],[[176,0],[249,99]]] 
  columns: 5
  rows: 5
  goal: !!python/tuple [2, 3]
  start: !!python/tuple [2, 0]
  beacons_columns: [2, 4, 0, 4, 0]
  beacons_rows: [4, 2, 4, 4, 2]
  orientation_reference_row: 4

kalman:
 Q: 0.17
 R: 0.08
 P0: 10000
 X0: 0.75
