beacon:
  # known object width (cm)
  real_width: 8.5
  # camera-lenses real world distance (cm) from robot centre
  distance_from_reference_pic: 7
  # colour boundaries when in HSV: H (0-180) | S (0-255) | V (0-255)
  hsv_color_boundaries:
  - - !!python/tuple # Red
      - [0, 100 , 130]
      - [10, 230 , 230]
  - - !!python/tuple # Blue
      - [70,70, 90]
      - [110,220,170]
  - - !!python/tuple # Purple
      - [90,0,40]
      - [160,135,135]
  - - !!python/tuple # Yellow
      - [20,170,100]
      - [35, 255, 210 ]
  - - !!python/tuple # Green
      - [40, 120, 90]
      - [60, 255, 200]
  - - !!python/tuple # Black
      - [15, 40, 40]
      - [50, 200, 90]

  rgb_color_boundaries:
  - - !!python/tuple # Red 
      - [70, 60, 200]
      - [150, 110, 250]
  - - !!python/tuple # Blue
      - [160, 160, 0]
      - [255, 255, 60]
  - - !!python/tuple # Purple
      - [95, 80, 95]
      - [130, 110, 120]
  - - !!python/tuple # Yellow
      - [30, 130, 130]
      - [80, 170, 160]
  - - !!python/tuple # Orange
      - [70, 100, 190]
      - [145, 140, 240] 

camera: 
  focal_length: 4305 
  # x-centre-coordinate of the 2596x1944 resolution picture
  pic_centre_width: 1296
  vertical_servo_pin: 27

grid:
  #grid_size: 25
  #cell_size: 10
  #distance_to_neighbours: 30 
  #destination: ["13:18:W","18:18:W"]
  #obstacles : [[[0,90],[99,110]],[[176,0],[249,99]]] 
  #columns: 25
  #rows: 25
  #goal: !!python/tuple [13, 18]
  #start: !!python/tuple [0, 0]
  #beacons_columns: [10, 20, 0, 20, 0]
  #beacons_rows: [20, 10, 20, 20, 10]
  #orientation_reference_row: 20
  grid_size: 25
  cell_size: 10
  distance_to_neighbours: 20 
  destination: ["5:10:N","18:14:E",]
  obstacles : [[[70,90],[100,160]],[[180,110],[230,140]]] 
  columns: 25
  rows: 25
  beacons_columns: [13, 24, 0, 0, 1, 24] #13, 24]
  beacons_rows: [24, 14, 0, 10, 24, 23] # 0 , 23]
  orientation_reference_row: 24

kalman:
 Q: 0.17
 R: 0.08
 P0: 10000
 X0: 0.75
